### PR TITLE
test(endpoints): add unit test for validators

### PR DESCRIPTION
**Pull request by lvamaral**
what: add unit tests for endpoint validators
why: to ensure integrity of our endpoints

### CODE REVIEW

**Review by pallavi — APPROVED** [review]
LGTM!
can you add `coverage` to your `.gitignore` file and remove the coverage directory so that your next PR won't include all the coverage files?

**Review by virtualdom — CHANGES_REQUESTED** [review]
Everything looks gucci, but I'll LGTM once `coverage/` is added to your `.gitignore` 👍

**Comment by lvamaral** [comment]
@virtualdom the new PRs had it but I've updated this one too to add to .gitignore!

**Comment by virtualdom** [comment]
Make sure the `coverage/` folder doesn't get checked in as part of this PR!

**Review by virtualdom — APPROVED** [review]
Looks good!!!

**Pull request merged**
